# Generated by Django 3.2.4 on 2022-01-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=30)),
                ('Number', models.CharField(max_length=12)),
                ('DOB', models.DateField()),
                ('Password', models.CharField(max_length=25)),
                ('ConfirmPassword', models.CharField(max_length=25)),
            ],
        ),
    ]
